name: Update Activity Graph

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Activity Graph
        uses: Ashutosh00710/github-readme-activity-graph@main
        with:
          username: ${{ github.repository_owner }}
          theme: github-dark
          output_dir: dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: activity-graph-output
